#!/usr/bin/env sh

server="/home/$USER/.vim/servers"

java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -noverify -Xms1G -jar "$server/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar" -configuration "$server/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux/" "$@"

