foreground   #EEF0F9
background   #17191E
cursor       #EEF0F9

selection_background #343841
selection_foreground #EEF0F9

color0  #17191E
color1  #FF63A5
color2  #4BF3C8
color3  #FFD493
color4  #54B9FF
color5  #B180D7
color6  #00DAEF
color7  #BFC1C9

color8   #424450
color9   #FF75B3
color10  #61F7D9
color11  #FFE7A1
color12  #7EC9FF
color13  #C798E8
color14  #80E6F2
color15  #F0F0F5

active_tab_foreground   #17191E
active_tab_background   #54B9FF
inactive_tab_foreground #BFC1C9
inactive_tab_background #343841
