include current-theme.conf

# Remote control — required for context-aware SUPER+N tab switching
allow_remote_control yes
listen_on unix:@kitty

# Kitty layouts
enabled_layouts tall,fat,grid,splits

enable_kitty_keyboard_protocol yes
shell fish
font_family DejaVuSansM Nerd Font Mono
font_size 12.0
strip_trailing_spaces smart
enable_audio_bell no
visual_bell_duration 0.0
cursor_shape beam
tab_bar_edge top
tab_bar_style separator
tab_separator ""
tab_title_template " {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title} "

clear_all_shortcuts yes
kitty_mod ctrl+shift

map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+shift+home no_op
map ctrl+shift+end no_op
map ctrl+t new_tab_with_cwd
map alt+t new_tab_with_cwd
map ctrl+w close_tab
map alt+w close_tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+left previous_tab
map alt+right next_tab
map shift+alt+left move_tab_backward
map shift+alt+right move_tab_forward
map ctrl+c copy_and_clear_or_interrupt
map kitty_mod+c copy
map ctrl+v paste_from_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+page_up scroll_page_up
map kitty_mod+page_down scroll_page_down
map kitty_mod+f5 load_config_file
map kitty_mod+f6 debug_config
