#!/bin/bash

res=$(dmenu < ~/.i3/poweroptions)

if [ $res = "lock" ]; then
	i3exit lock
fi
if [ $res = "suspend" ]; then
	i3exit suspend
fi
if [ $res = "switch user" ]; then
	i3exit switch_user
fi
if [ $res = "logout" ]; then
	i3exit logout
fi
if [ $res = "hibernate" ]; then
	i3exit hibernate
fi
if [ $res = "reboot" ]; then
	i3exit reboot 
fi
if [ $res = "shutdown" ]; then
	i3exit shutdown
fi
exit 0
