#!/bin/bash

res=$(dmenu < ~/.config/i3/poweroptions)

if [ $res = "lock" ]; then
	i3exit lock
fi
if [ $res = "logout" ]; then
	i3-msg exit
fi
if [ $res = "switch user" ]; then
	i3exit switch_user
fi
if [ $res = "reboot" ]; then
	reboot
fi
if [ $res = "poweroff" ]; then
	poweroff
fi
exit 0
