#!/bin/bash

res=$(dmenu < ~/.config/i3/poweroptions)

if [ $res = "lock" ]; then
	i3lock-fancy -f DejaVu-Sans-Mono -- scrot -z
fi
if [ $res = "logout" ]; then
	i3-msg exit
fi
if [ $res = "reboot" ]; then
	reboot
fi
if [ $res = "poweroff" ]; then
	poweroff
fi
exit 0
