#!/bin/bash
if synclient -l | grep "TouchpadOff .*=.*0" ; then
    synclient TouchpadOff=1 ;
    xinput set-prop "TPPS/2 IBM TrackPoint" "Device Enabled" 1 ;
else
    synclient TouchpadOff=0 ;
    xinput set-prop "TPPS/2 IBM TrackPoint" "Device Enabled" 0 ;
fi
