# hyprpaper.conf

wallpaper {
  monitor = DP-3
  path = ~/Images/Wallpapers/1.jpg
  # path = ~/Images/Wallpapers/2.png
  fit_mode = contain
}

wallpaper {
  monitor = eDP-2
  path = ~/Images/Wallpapers/neon.png
  fit_mode = cover
}

splash = false
ipc = off
