# hyprlock.conf
general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    color = rgba(181818ff)
}

input-field {
    monitor =
    size = 300, 50
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 2
    outer_color = rgb(7129FF)
    inner_color = rgb(181818)
    font_color = rgb(5C78FF)
    placeholder_text = Password...
    fail_text = <b>Wrong password</b>
    fail_color = rgb(ff5555)
    capslock_color = rgb(ffaa00)
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgba(5C78FFff)
    font_size = 48
    font_family = DejaVuSansM Nerd Font Mono
    position = 0, 80
    halign = center
    valign = center
}
