# hyprpaper.conf

# 1.png fit_mode = contain
# 2.jpg fit_mode = contain
# 3.jpeg fit_mode = fit

wallpaper {
  monitor = DP-3
  # path = ~/Images/Wallpapers/1.png
  path = ~/Images/Wallpapers/2.jpg
  # path = ~/Images/Wallpapers/3.jpeg
  fit_mode = contain
  # fit_mode = fit
}

wallpaper {
  monitor = eDP-2
  path = ~/Images/Wallpapers/neon.png
  fit_mode = cover
}

splash = false
ipc = off
