set encoding=utf-8
set number
set tabstop=4
set noshowmode
set listchars=tab:▸‒,space:·,eol:↩
set list
set ttimeoutlen=0
set shiftwidth=4
set termguicolors
set cursorline
set wildmenu
set showmatch
set incsearch
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent
set hidden
